[package]
name = "rust-nlp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sudachi = { path = "../sudachi/sudachi" }
# sudachi = { git = "https://github.com/WorksApplications/sudachi.rs.git" }
